--- 
- name: Install and configure SNMP
  hosts: all
  become: yes

  tasks:
  - name: Install SNMP package
    package:
      name: net-snmp
      state: present

  - name: Configure SNMP settings
    ansible.snmp.snmp_config:
      community: "server"
      access: 
        -  "server"  
          security: "noAuthNoPriv"
          source: 0.0.0.0/0

  - name: Verify SNMP connectivity
    ansible.snmp.get:
      oid: "SNMPv2-MIB::sysDescr.0"
      community: "server"
    register: snmp_response
    delegate_to: librenms.csd509j.net
    failed_when: snmp_response.failed

  - debug: var=snmp_response.response
